//! First-run MPD configuration: when no daemon config exists, create a
//! local Unix-socket setup that accepts file:// songs without a music root.

use std::{
  io::ErrorKind,
  path::{Path, PathBuf},
};

use anyhow::{Context, Result};
use tokio::{fs, io::AsyncWriteExt};

#[cfg(target_os = "macos")]
use super::paths::env_path;
use super::paths::{mpd_config_paths, platform_cache_dir, platform_config_dir};

pub(super) struct MpdBootstrap {
  pub socket_path: PathBuf,
}

struct BootstrapPaths {
  config: PathBuf,
  socket: PathBuf,
  playlists: PathBuf,
  database: PathBuf,
  log: PathBuf,
  state: PathBuf,
  sticker: PathBuf,
}

pub(super) async fn ensure_mpd_config() -> Result<Option<MpdBootstrap>> {
  if startup_config_paths().iter().any(|path| path.is_file()) {
    return Ok(None);
  }
  let Some(paths) = bootstrap_paths() else {
    return Ok(None);
  };
  create_config(&paths).await
}

fn startup_config_paths() -> Vec<PathBuf> {
  mpd_config_paths()
}

fn bootstrap_paths() -> Option<BootstrapPaths> {
  let config_root = platform_config_dir().join("mpd");
  let cache_root = platform_cache_dir().join("mpd");
  #[cfg(target_os = "macos")]
  let config = env_path("HOME")?.join(".mpd").join("mpd.conf");
  #[cfg(not(target_os = "macos"))]
  let config = config_root.join("mpd.conf");
  Some(BootstrapPaths {
    config,
    socket: config_root.join("socket"),
    playlists: config_root.join("playlists"),
    database: cache_root.join("database"),
    log: cache_root.join("log"),
    state: cache_root.join("state"),
    sticker: cache_root.join("sticker.sql"),
  })
}

async fn create_config(paths: &BootstrapPaths) -> Result<Option<MpdBootstrap>> {
  for dir in [
    paths.config.parent(),
    paths.socket.parent(),
    Some(paths.playlists.as_path()),
    paths.database.parent(),
  ]
  .into_iter()
  .flatten()
  {
    fs::create_dir_all(dir)
      .await
      .with_context(|| format!("failed to create MPD directory {}", dir.display()))?;
  }

  let body = render_config(paths);
  let opened = fs::OpenOptions::new()
    .write(true)
    .create_new(true)
    .open(&paths.config)
    .await;
  let mut file = match opened {
    Ok(file) => file,
    Err(error) if error.kind() == ErrorKind::AlreadyExists => return Ok(None),
    Err(error) => {
      return Err(error)
        .with_context(|| format!("failed to create MPD config {}", paths.config.display()));
    }
  };
  if let Err(error) = file.write_all(body.as_bytes()).await {
    drop(file);
    let _ = fs::remove_file(&paths.config).await;
    return Err(error)
      .with_context(|| format!("failed to write MPD config {}", paths.config.display()));
  }
  Ok(Some(MpdBootstrap {
    socket_path: paths.socket.clone(),
  }))
}

fn render_config(paths: &BootstrapPaths) -> String {
  format!(
    "# Generated by music-tui. Local files are queued over the Unix socket;\n\
     # no music_directory is required. Existing MPD configs are never overwritten.\n\
     playlist_directory \"{}\"\n\
     db_file \"{}\"\n\
     log_file \"{}\"\n\
     state_file \"{}\"\n\
     sticker_file \"{}\"\n\n\
     bind_to_address \"{}\"\n",
    mpd_escape(&paths.playlists),
    mpd_escape(&paths.database),
    mpd_escape(&paths.log),
    mpd_escape(&paths.state),
    mpd_escape(&paths.sticker),
    mpd_escape(&paths.socket),
  )
}

fn mpd_escape(path: &Path) -> String {
  path
    .to_string_lossy()
    .replace('\\', "\\\\")
    .replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn generated_config_uses_socket_without_music_directory() {
    let root = Path::new("/tmp/music tui");
    let paths = BootstrapPaths {
      config: root.join("mpd.conf"),
      socket: root.join("mpd socket"),
      playlists: root.join("playlists"),
      database: root.join("database"),
      log: root.join("log"),
      state: root.join("state"),
      sticker: root.join("sticker.sql"),
    };
    let body = render_config(&paths);
    assert!(body.contains("bind_to_address \"/tmp/music tui/mpd socket\""));
    assert!(body.contains("playlist_directory \"/tmp/music tui/playlists\""));
    assert!(!body.contains("\nmusic_directory "));
  }

  #[tokio::test]
  async fn config_creation_is_non_destructive() {
    let unique = std::time::SystemTime::now()
      .duration_since(std::time::UNIX_EPOCH)
      .unwrap()
      .as_nanos();
    let root = std::env::temp_dir().join(format!("music-tui-mpd-bootstrap-{unique}"));
    let paths = BootstrapPaths {
      config: root.join("config/mpd.conf"),
      socket: root.join("runtime/socket"),
      playlists: root.join("playlists"),
      database: root.join("cache/database"),
      log: root.join("cache/log"),
      state: root.join("cache/state"),
      sticker: root.join("cache/sticker.sql"),
    };

    let created = create_config(&paths).await.unwrap();
    assert!(created.is_some());
    let original = fs::read_to_string(&paths.config).await.unwrap();
    assert!(original.contains("bind_to_address"));

    fs::write(&paths.config, "custom config\n").await.unwrap();
    assert!(create_config(&paths).await.unwrap().is_none());
    assert_eq!(
      fs::read_to_string(&paths.config).await.unwrap(),
      "custom config\n"
    );

    let _ = fs::remove_dir_all(root).await;
  }
}
